# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` 

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [4]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10

In [10]:
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array 

In [18]:
null_vec.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line?

In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [22]:
vec = np.zeros(10)
vec[5] = 1
print(vec)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49

In [43]:
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last)


In [45]:
vec = vec[::-1]
print(vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [51]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [64]:
given_arr = np.array([1,2,0,0,4,0])
non_zero_idx = np.nonzero(given_arr)[0]
print(non_zero_idx)

[0 1 4]


#### 11. Create a 3x3 identity matrix


In [58]:
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 12. Create a 3x3x3 array with random values

In [66]:
np.random.rand(3,3,3)

array([[[0.49342737, 0.37119871, 0.70030177],
        [0.56926677, 0.21879395, 0.18599657],
        [0.42454583, 0.9501963 , 0.61018012]],

       [[0.26769551, 0.2770168 , 0.9588631 ],
        [0.46938677, 0.40299596, 0.04579171],
        [0.04574043, 0.8336582 , 0.23745272]],

       [[0.84606812, 0.42160183, 0.43751079],
        [0.52718403, 0.24089235, 0.46053205],
        [0.29080319, 0.92887677, 0.6246931 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [74]:
arr = np.random.rand(10,10)
print(f"Max = {np.max(arr)} Min = {np.min(arr)}")

Max = 0.9630824700580828 Min = 0.011358572402803135


#### 14. Create a random vector of size 30 and find the mean value

In [86]:
vec = np.random.rand(30)
print(vec)
print(f"Mean = {np.mean(vec)}")

[0.60303924 0.68979865 0.8121607  0.32686734 0.70736846 0.86464547
 0.26157137 0.21483075 0.57049036 0.94001588 0.11811048 0.30757193
 0.66414218 0.26749571 0.74654105 0.98144519 0.16712223 0.27299295
 0.26817856 0.13094978 0.43515996 0.04821357 0.10240187 0.85449051
 0.18393297 0.50514208 0.54157931 0.01239591 0.1081892  0.77739804]
Mean = 0.44947472330182514


#### 15. Create a 2d array with 1 on the border and 0 inside

In [90]:
arr = np.ones(100).reshape(10,10)
arr[1:-1, 1:-1] = 0

```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

#### 16. How to add a border (filled with 0's) around an existing array?

In [94]:
arr_size = 10
arr = np.ones(arr_size**2).reshape(arr_size,arr_size)
arr_2 = np.zeros((arr_size+2)**2).reshape(arr_size+2,arr_size+2)
arr_2[1:-1,1:-1] = arr
print (arr_2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [101]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [105]:
mat = np.diag([1,2,3,4], k=-1)
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [111]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [117]:
array = np.empty((6,7,8))
index = np.unravel_index(99, array.shape)
print(index)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [120]:
checkerboard = np.array([[0, 1], [1, 0]])
checkerboard_8x8 = np.tile(checkerboard, (4, 4))

print(checkerboard_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [199]:
random_array = np.random.rand(5, 5)*10

min_val = random_array.min()
max_val = random_array.max()

normalized_array = (random_array - min_val) / (max_val - min_val)

print(normalized_array)

[[0.22769741 0.66871871 0.2094462  0.         0.36515414]
 [0.21923296 0.43983775 0.60517497 0.4871407  0.28404325]
 [0.98347073 1.         0.58615159 0.69631225 0.67788066]
 [0.81197033 0.75981383 0.87444704 0.95361496 0.06221967]
 [0.54730896 0.77603792 0.22065608 0.38307724 0.14080754]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [152]:
color_dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])

print(color_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


In [154]:
color_data = np.array([(255, 0, 0, 255), (0, 255, 0, 255)], dtype=color_dtype)

print(color_data)

[(255,   0, 0, 255) (  0, 255, 0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [148]:
arr1 = np.random.randint(1,99, size=(5,3))
arr2 = np.random.randint(1,99, size=(3,2))
arr1.dot(arr2)
print(f"{arr1=}")
print(f"{arr2=}")
print(f"{arr1.dot(arr2)=}")

arr1=array([[23, 45,  4],
       [73, 13, 88],
       [81, 65, 38],
       [20, 44,  9],
       [97, 54, 20]])
arr2=array([[81, 84],
       [84, 37],
       [67, 93]])
arr1.dot(arr2)=array([[ 5911,  3969],
       [12901, 14797],
       [14567, 12743],
       [ 5919,  4145],
       [13733, 12006]])


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [156]:
arr = np.array([1, 4, 6, 9, 7, 2, 5, 3, 8])
arr[(arr > 3) & (arr < 8)] *= -1

print(arr)

[ 1 -4 -6  9 -7  2 -5  3  8]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [158]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [234]:
Z = np.array([1, 2, 3, 4, 5])

# Check the legality of the expressions
result1 = Z**Z
result2 = 2 << Z >> 2
result3 = Z <- Z
result4 = 1j*Z
result5 = Z/1/1
# result6 = Z<Z>Z  # This line is not a legal expression

# Print the results
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)

[   1    4   27  256 3125]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[1. 2. 3. 4. 5.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [170]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\mughe\AppData\Local\Temp\ipykernel_13820\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\mughe\AppData\Local\Temp\ipykernel_13820\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\mughe\AppData\Local\Temp\ipykernel_13820\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ?

In [174]:
float_array = np.array([1.2, 2.7, -3.5, -4.8, 5.1])

rounded_up = np.ceil(float_array)
rounded_down = np.floor(float_array)

print("Original array:", float_array)
print("Rounded up (away from zero):", rounded_up)
print("Rounded down (away from zero):", rounded_down)

Original array: [ 1.2  2.7 -3.5 -4.8  5.1]
Rounded up (away from zero): [ 2.  3. -3. -4.  6.]
Rounded down (away from zero): [ 1.  2. -4. -5.  5.]


#### 30. How to find common values between two arrays?

In [177]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

np.intersect1d(array1, array2)

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)?

In [183]:
np.seterr(all='ignore')
# np.seterr(all='warn')

{'divide': 'warn', 'over': 'warn', 'under': 'warn', 'invalid': 'warn'}

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [185]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\mughe\AppData\Local\Temp\ipykernel_13820\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [187]:
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow?

In [189]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-07-04
Today: 2024-07-05
Tomorrow: 2024-07-06


#### 34. How to get all the dates corresponding to the month of July 2016?

In [191]:
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print("Dates in July 2016:")
print(dates_july_2016)

Dates in July 2016:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [195]:
A = np.array([1, 2, 3], dtype=np.float64)
B = np.array([4, 5, 6])

result = np.empty_like(A)
np.add(A, B, out=result)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(result, A, out=result)

print(result)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [197]:
random_array = np.random.random((5, 5)) * 10

integer_part_floor = np.floor(random_array)
integer_part_astype = random_array.astype(int)
integer_part_vectorize = np.vectorize(int)(random_array)
integer_part_trunc = np.trunc(random_array)

print("Original Array:\n", random_array)
print("\nInteger Part using np.floor:\n", integer_part_floor)
print("\nInteger Part using astype(int):\n", integer_part_astype)
print("\nInteger Part using np.vectorize with int:\n", integer_part_vectorize)
print("\nInteger Part using np.trunc:\n", integer_part_trunc)

Original Array:
 [[3.57171537 8.33848332 6.74531345 8.20322519 1.652237  ]
 [9.34180336 9.66987497 5.30587675 6.5076282  3.97735923]
 [3.91423774 5.07084852 2.98966245 6.79817537 1.59592122]
 [0.47875393 1.03627485 6.44016267 2.08084935 8.81552336]
 [2.94702281 0.57985114 7.38034757 2.26291763 8.33616426]]

Integer Part using np.floor:
 [[3. 8. 6. 8. 1.]
 [9. 9. 5. 6. 3.]
 [3. 5. 2. 6. 1.]
 [0. 1. 6. 2. 8.]
 [2. 0. 7. 2. 8.]]

Integer Part using astype(int):
 [[3 8 6 8 1]
 [9 9 5 6 3]
 [3 5 2 6 1]
 [0 1 6 2 8]
 [2 0 7 2 8]]

Integer Part using np.vectorize with int:
 [[3 8 6 8 1]
 [9 9 5 6 3]
 [3 5 2 6 1]
 [0 1 6 2 8]
 [2 0 7 2 8]]

Integer Part using np.trunc:
 [[3. 8. 6. 8. 1.]
 [9. 9. 5. 6. 3.]
 [3. 5. 2. 6. 1.]
 [0. 1. 6. 2. 8.]
 [2. 0. 7. 2. 8.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [201]:
matrix = np.tile(np.arange(5), (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [211]:
def gen_func():
    for i in range(10):
        yield i

gen = gen_func()
arr = np.fromiter(gen, dtype=int)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [215]:
np.linspace(0,1,12,endpoint=False)[1:-1]

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333])

#### 40. Create a random vector of size 10 and sort it

In [223]:
vec = np.sort(np.random.rand(10))
print(vec)

[0.00924038 0.12274579 0.21152721 0.39122828 0.57389803 0.58812342
 0.69904221 0.75141422 0.86983338 0.92089961]


#### 41. How to sum a small array faster than np.sum?

Using simple python built-in sum function

#### 42. Consider two random array A and B, check if they are equal

In [228]:
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
np.array_equal(arr1, arr2)

False

#### 43. Make an array immutable (read-only) 

In [238]:
arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False
arr[0] = 10  # Uncomment this line to see the error

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [240]:
cartesian_coords = np.random.random((10, 2))

x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar_coords = np.column_stack((r, theta))

print("Cartesian Coordinates:\n", cartesian_coords)
print("\nPolar Coordinates:\n", polar_coords)

Cartesian Coordinates:
 [[0.1839557  0.75240444]
 [0.53893587 0.05941924]
 [0.79009265 0.8188907 ]
 [0.54428731 0.08881417]
 [0.16461229 0.06912514]
 [0.30890966 0.23984628]
 [0.8601111  0.52411646]
 [0.25245728 0.50854167]
 [0.15604381 0.42387072]
 [0.97850379 0.69466214]]

Polar Coordinates:
 [[0.77456577 1.33100981]
 [0.54220155 0.10980939]
 [1.13790525 0.80329454]
 [0.55148584 0.16174962]
 [0.17853709 0.39756588]
 [0.39109004 0.66020195]
 [1.00721853 0.54727273]
 [0.56775814 1.11000574]
 [0.45168137 1.21805333]
 [1.20001048 0.61735456]]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [250]:
vec = np.random.rand(10)
print(vec)
vec[np.argmax(vec)] = 0
print(vec)

[0.1741699  0.02524246 0.19607972 0.44680041 0.22043107 0.84803371
 0.3974871  0.66559183 0.62776258 0.14000208]
[0.1741699  0.02524246 0.19607972 0.44680041 0.22043107 0.
 0.3974871  0.66559183 0.62776258 0.14000208]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [265]:
num_points = 10

grid = np.zeros((num_points*num_points,), dtype=[('x', float), ('y', float)])

# Generate x and y coordinates
x_coords, y_coords = np.meshgrid(np.linspace(0, 1, num_points), np.linspace(0, 1, num_points))

grid['x'] = x_coords.ravel()
grid['y'] = y_coords.ravel()

print(grid)

[(0.        , 0.        ) (0.11111111, 0.        )
 (0.22222222, 0.        ) (0.33333333, 0.        )
 (0.44444444, 0.        ) (0.55555556, 0.        )
 (0.66666667, 0.        ) (0.77777778, 0.        )
 (0.88888889, 0.        ) (1.        , 0.        )
 (0.        , 0.11111111) (0.11111111, 0.11111111)
 (0.22222222, 0.11111111) (0.33333333, 0.11111111)
 (0.44444444, 0.11111111) (0.55555556, 0.11111111)
 (0.66666667, 0.11111111) (0.77777778, 0.11111111)
 (0.88888889, 0.11111111) (1.        , 0.11111111)
 (0.        , 0.22222222) (0.11111111, 0.22222222)
 (0.22222222, 0.22222222) (0.33333333, 0.22222222)
 (0.44444444, 0.22222222) (0.55555556, 0.22222222)
 (0.66666667, 0.22222222) (0.77777778, 0.22222222)
 (0.88888889, 0.22222222) (1.        , 0.22222222)
 (0.        , 0.33333333) (0.11111111, 0.33333333)
 (0.22222222, 0.33333333) (0.33333333, 0.33333333)
 (0.44444444, 0.33333333) (0.55555556, 0.33333333)
 (0.66666667, 0.33333333) (0.77777778, 0.33333333)
 (0.88888889, 0.33333333) (1.  

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [268]:
def cauchy_matrix(X, Y):
    m = len(X)
    n = len(Y)
    C = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            C[i, j] = 1 / (X[i] - Y[j])
    return C

X = np.array([1, 2, 3])
Y = np.array([4, 5])
C = cauchy_matrix(X, Y)
print("Cauchy Matrix C:")
print(C)

Cauchy Matrix C:
[[-0.33333333 -0.25      ]
 [-0.5        -0.33333333]
 [-1.         -0.5       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [272]:
scalar_types = [
    ('bool', bool, np.bool_(True), np.bool_(False)),
    ('int8', np.int8, np.iinfo(np.int8).min, np.iinfo(np.int8).max),
    ('uint8', np.uint8, np.iinfo(np.uint8).min, np.iinfo(np.uint8).max),
    ('int16', np.int16, np.iinfo(np.int16).min, np.iinfo(np.int16).max),
    ('uint16', np.uint16, np.iinfo(np.uint16).min, np.iinfo(np.uint16).max),
    ('int32', np.int32, np.iinfo(np.int32).min, np.iinfo(np.int32).max),
    ('uint32', np.uint32, np.iinfo(np.uint32).min, np.iinfo(np.uint32).max),
    ('int64', np.int64, np.iinfo(np.int64).min, np.iinfo(np.int64).max),
    ('uint64', np.uint64, np.iinfo(np.uint64).min, np.iinfo(np.uint64).max),
    ('float16', np.float16, np.finfo(np.float16).min, np.finfo(np.float16).max),
    ('float32', np.float32, np.finfo(np.float32).min, np.finfo(np.float32).max),
    ('float64', np.float64, np.finfo(np.float64).min, np.finfo(np.float64).max),
]

for name, typ, min_val, max_val in scalar_types:
    print(f"{name}:")
    print(f"  Min: {min_val}")
    print(f"  Max: {max_val}")
    print()


bool:
  Min: True
  Max: False

int8:
  Min: -128
  Max: 127

uint8:
  Min: 0
  Max: 255

int16:
  Min: -32768
  Max: 32767

uint16:
  Min: 0
  Max: 65535

int32:
  Min: -2147483648
  Max: 2147483647

uint32:
  Min: 0
  Max: 4294967295

int64:
  Min: -9223372036854775808
  Max: 9223372036854775807

uint64:
  Min: 0
  Max: 18446744073709551615

float16:
  Min: -65504.0
  Max: 65504.0

float32:
  Min: -3.4028234663852886e+38
  Max: 3.4028234663852886e+38

float64:
  Min: -1.7976931348623157e+308
  Max: 1.7976931348623157e+308



#### 49. How to print all the values of an array? 

In [286]:
arr = np.random.rand(10)*10
for val in arr: 
    print(val)


7.654006323722163
2.9730292990305642
9.816860665794403
2.5515184835674
6.453059331414433
4.79995045863202
1.0084745335441714
4.585181902136473
7.666227377929404
2.971544726526163


#### 50. How to find the closest value (to a given scalar) in a vector?

In [290]:
vector = np.array([3, 8, 1, 6, 2])
scalar_value = 9
closest_index = np.argmin(np.abs(vector - scalar_value))
closest_value = vector[closest_index]

print(f"Vector: {vector}")
print(f"Scalar value: {scalar_value}")
print(f"Closest value in vector to {scalar_value}: {closest_value}")

Vector: [3 8 1 6 2]
Scalar value: 9
Closest value in vector to 9: 8


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [296]:
dtype = [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])]

positions_colors = np.array([
    ((10.0, 20.0), (255, 0, 0)),
    ((5.5, 15.2), (0, 255, 0)),
    ((8.8, 25.3), (0, 0, 255)),
], dtype=dtype)

print("First element:")
print(f"Position: ({positions_colors['position']['x'][0]}, {positions_colors['position']['y'][0]})")
print(f"Color: ({positions_colors['color']['r'][0]}, {positions_colors['color']['g'][0]}, {positions_colors['color']['b'][0]})")

First element:
Position: (10.0, 20.0)
Color: (255, 0, 0)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [400]:
coors = np.random.rand(100, 2)
x = coors[:, 0]
y = coors[:, 1]
distances = np.sqrt(x**2+y**2)

print(distances)

[1.00338137 0.57136864 0.13342171 0.27438444 0.59528241 0.85366355
 1.03272789 0.6228032  0.31211648 0.94456198 0.16026433 0.84713944
 0.74764602 0.64107217 1.26244146 0.84320794 0.42226419 0.78571189
 0.24041937 0.39893835 0.99888663 0.82777715 0.21760829 0.83983037
 0.70277969 1.12532456 0.83645407 0.48087365 0.37091959 0.81134511
 0.80458156 0.92452174 1.00836773 0.50433564 0.36400095 0.19980899
 0.61929815 1.07271902 0.63570437 0.35863927 0.99815383 0.93897871
 0.53607324 0.73906029 0.96901626 0.85346939 0.67588548 0.52276731
 1.28162759 0.58862932 0.4651339  0.7770271  0.76082742 0.74855525
 0.83642545 0.77303862 0.95097607 0.3909446  0.7523967  0.7103488
 0.93724518 1.12868197 0.49735349 0.76243334 0.66624797 0.95355426
 1.22325039 0.9904893  0.44976571 0.67985263 0.8729365  0.44367626
 0.62952758 0.84988272 1.05540589 0.5363207  0.8477374  0.73329798
 0.9232341  1.28598896 1.01519558 0.45758197 0.29560376 0.55831688
 0.30490769 0.09998325 1.13476783 0.88358204 1.0808151  1.16146

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [305]:
float_array = np.array([1.5, 2.7, 3.9, 4.2], dtype=np.float32)

float_array_view = float_array.view(dtype=np.int32)
float_array_view[:] = float_array[:]

print("Integer array (32-bit):", float_array_view)

Integer array (32-bit): [1 2 3 4]


#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [390]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays?

In [308]:
arr = np.array([[1, 2], [3, 4]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array

In [325]:
def gaussian_2d(shape, amplitude=1.0, center=(0.0, 0.0), sigma=1.0):
    x0, y0 = center
    x, y = np.meshgrid(np.arange(shape[1]), np.arange(shape[0]))
    exponent = -((x - x0)**2 + (y - y0)**2) / (2 * sigma**2)
    gaussian = amplitude * np.exp(exponent)
    return gaussian

shape = (100, 100)
amplitude = 1.0
center = (shape[0] // 2, shape[1] // 2)
sigma = 20.0

gaussian_array = gaussian_2d(shape, amplitude, center, sigma)

print(gaussian_array)

[[0.00193045 0.00218476 0.00246639 ... 0.00277737 0.00246639 0.00218476]
 [0.00218476 0.00247256 0.00279129 ... 0.00314324 0.00279129 0.00247256]
 [0.00246639 0.00279129 0.00315111 ... 0.00354843 0.00315111 0.00279129]
 ...
 [0.00277737 0.00314324 0.00354843 ... 0.00399585 0.00354843 0.00314324]
 [0.00246639 0.00279129 0.00315111 ... 0.00354843 0.00315111 0.00279129]
 [0.00218476 0.00247256 0.00279129 ... 0.00314324 0.00279129 0.00247256]]


#### 57. How to randomly place p elements in a 2D array?

In [349]:
shape = (5, 5)
p = 7
value = 1

arr = np.zeros(shape, dtype=int)

total_elements = shape[0] * shape[1]
flat_indices = np.random.choice(total_elements, p, replace=False)

indices = np.unravel_index(flat_indices, shape)

arr[indices] = value

print("Randomly placed array:")
print(arr)

Randomly placed array:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 1 0]
 [1 1 0 0 1]
 [0 1 1 0 0]]


#### 58. Subtract the mean of each row of a matrix

In [361]:
X = np.random.rand(5, 5)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 0.18893656  0.05705126 -0.27490413  0.25510135 -0.22618505]
 [-0.36815234 -0.10865586  0.01995092  0.39438054  0.06247675]
 [-0.38227285 -0.34942356  0.385915    0.39987118 -0.05408977]
 [ 0.07433946  0.09447867 -0.10605082 -0.14098947  0.07822216]
 [ 0.47473899  0.11962451 -0.15480174 -0.28833302 -0.15122874]]


#### 59. How to sort an array by the nth column?

In [373]:
arr = np.random.randint(0,10,(3,3))
n = 1
sorted_arr = arr[np.argsort(arr[:, n])]

print("Original array:")
print(arr)
print("\nSorted array by the nth column:")
print(sorted_arr)

Original array:
[[5 3 2]
 [2 2 6]
 [0 3 9]]

Sorted array by the nth column:
[[2 2 6]
 [5 3 2]
 [0 3 9]]


#### 60. How to tell if a given 2D array has null columns?

In [392]:
import numpy as np

def has_null_columns(arr):
    return np.any(np.all(arr == 0, axis=0))

arr = np.random.randint(0,10,(3,3))
print(has_null_columns(arr))

False


#### 61. Find the nearest value from a given value in an array

In [402]:
arr = np.random.randint(0, 100, size=10)
given_value = 40
nearest_value = arr[np.abs(arr - given_value).argmin()]

print("Array:", arr)
print("Nearest value:", nearest_value)

Array: [17 32 28 23 86 78  5 12 57  7]
Nearest value: 32


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [407]:


# Example arrays
arr1 = np.array([[1, 2, 3]])  # Shape (1, 3)
arr2 = np.array([[1],
                 [2],
                 [3]])           # Shape (3, 1)

# Compute sum using an iterator
iterator_sum = sum(x + y for x, y in zip(arr1.flat, arr2.flat))

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nSum computed with iterator:", iterator_sum)


Array 1:
[[1 2 3]]

Array 2:
[[1]
 [2]
 [3]]

Sum computed with iterator: 12


C:\Users\mughe\AppData\Local\Temp\ipykernel_13820\3305426672.py:8: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  iterator_sum = sum(x + y for x, y in zip(arr1.flat, arr2.flat))


In [415]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
iter = np.nditer([A,B,None])
for x,y,z in iter: 
    z[...] = x + y
print(iter.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute

In [427]:
import numpy as np

class NamedArray:
    def __init__(self, name, array):
        self.name = name
        self.array = np.array(array)

# Example usage:
arr = NamedArray("Example Array", [[1, 2, 3], [4, 5, 6]])

print(arr.name)
print(arr.array)

Example Array
[[1 2 3]
 [4 5 6]]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [470]:
arr = np.ones(10)*10
idx = np.random.randint(0,len(Z),10)

np.add.at(arr, idx, 1)
print(Z)

[ 5.  9.  1.  5. 13.  9.  9. 17.  9. 13.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [480]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 1, 3])
F = np.zeros(5)

np.add.at(F, I, X)

F

array([1., 6., 3., 5., 0.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [490]:
w, h = 128, 128

I = np.random.randint(0, 4, (w, h, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)

n = len(colors)
n

64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [500]:
A = np.random.randint(0,10,(3,4,3,4))
np.sum(A, axis=(2,-1))

array([[66, 56, 76, 60],
       [24, 59, 57, 34],
       [49, 48, 46, 34]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

In [504]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

subset_sums = np.bincount(S, weights=D)
subset_counts = np.bincount(S)
subset_means = subset_sums / subset_counts

print(subset_means)

[0.39770355 0.44456438 0.59233556 0.38477115 0.64002761 0.58322761
 0.67668288 0.49234392 0.45931683 0.49012336]


#### 69. How to get the diagonal of a dot product?

In [506]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([0.90863098, 1.05123202, 1.89799675, 0.9385121 , 1.57520057])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [510]:
vec = np.array([1, 2, 3, 4, 5])

num_zeros = 3
new_length = len(vec) + (len(vec) - 1) * num_zeros
new_vec = np.zeros(new_length)
new_vec[::num_zeros + 1] = vec

print(new_vec)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [518]:
A = np.ones((5,5,3))
B = np.random.randint(2,10,(5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [8. 8. 8.]
  [7. 7. 7.]
  [4. 4. 4.]
  [2. 2. 2.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [2. 2. 2.]
  [7. 7. 7.]
  [6. 6. 6.]]

 [[9. 9. 9.]
  [9. 9. 9.]
  [2. 2. 2.]
  [5. 5. 5.]
  [2. 2. 2.]]

 [[5. 5. 5.]
  [3. 3. 3.]
  [2. 2. 2.]
  [2. 2. 2.]
  [5. 5. 5.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [7. 7. 7.]
  [7. 7. 7.]]]


#### 72. How to swap two rows of an array?

In [532]:
arr = np.arange(9).reshape(3,3)
arr[[0,1]] = arr[[1,0]]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

In [568]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 24) ( 3, 96) ( 7, 20) ( 7, 70) (10, 24) (10, 73) (16, 22) (16, 56)
 (20, 70) (22, 56) (23, 52) (23, 71) (24, 73) (24, 96) (25, 48) (25, 99)
 (28, 31) (28, 35) (31, 34) (31, 35) (31, 44) (31, 72) (31, 73) (34, 44)
 (42, 64) (42, 81) (48, 99) (52, 71) (64, 81) (72, 73)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [570]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array?

In [572]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3
cum_sum = np.insert(np.cumsum(arr), 0, 0)  # Insert 0 at the beginning for correct subtraction
averages = (cum_sum[window_size:] - cum_sum[:-window_size]) / window_size
averages

array([2., 3., 4., 5., 6., 7., 8.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [694]:
def sliding_window(arr, window_size):
    result = []
    for i in range(len(arr) - window_size + 1):
        row = arr[i:i + window_size]
        result.append(row)
    return np.array(result)

# Example usage:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3

result = sliding_window(Z, window_size)
print(result)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace?

In [602]:
bool_array = np.array([True, False, True, False])
n_bool = np.logical_not(bool_array, out=bool_array)

float_array = np.array([1.0, -2.0, 3.5, -4.2])
n_float = np.negative(float_array, out=float_array)

f"{n_bool = }, {n_float = }"

'n_bool = array([False,  True, False,  True]), n_float = array([-1. ,  2. , -3.5,  4.2])'

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [630]:
def distance_point_to_line(P0, P1, p):
    x0, y0 = p[...,0], p[..., 1]
    
    x1, y1 = P0[:, 0], P0[:, 1]
    x2, y2 = P1[:, 0], P1[:, 1]

    numerator = np.abs((y2 - y1) * x0 - (x2 - x1) * y0 + x2 * y1 - y2 * x1)
    denominator = np.sqrt((y2 - y1)**2 + (x2 - x1)**2)
    distance = numerator / denominator
    
    return distance
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

distances = distance_point_to_line(P0, P1, p)
distances

array([ 5.79057183,  2.50134208, 12.4473279 ,  1.29586514, 13.57190462,
       14.83957534,  4.95141751,  4.64867324,  8.26270585,  4.66039468])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [638]:
# using the function from above problem
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,(10,2))

distances = [distance_point_to_line(P0,P1,x) for x in p] 

p, distances

(array([[ 3.38687855, -7.6582394 ],
        [-1.81423831, -5.33077855],
        [ 5.7564134 ,  5.29029903],
        [ 9.72152219, -8.23038126],
        [-2.91117273, -0.5049212 ],
        [ 1.29824826,  6.59823472],
        [-9.38160603,  5.20943903],
        [-9.00390936, -9.89213166],
        [ 3.02592787, -4.38375275],
        [ 6.84271051, -2.56786221]]),
 [array([ 6.40252499,  6.74249146,  4.65314685,  5.14741173, 11.49620145,
          9.79577637, 13.76199293,  3.87643495,  4.26151448,  7.1827726 ]),
  array([ 9.25864829,  1.11572928,  0.11201856,  0.19095641,  6.92286373,
          6.24495455, 12.2172209 ,  1.77927322,  0.09169454,  7.87253664]),
  array([ 3.09523427,  1.63807353,  4.97248304,  2.25288549,  1.35957315,
          2.15294475,  0.60638537,  0.78381564, 10.12405206,  5.13175377]),
  array([ 1.60012098, 12.35711403,  8.5515767 , 10.06120259, 15.09258074,
         11.92936134, 13.40501466,  9.59591921, 10.18999958,  4.40452642]),
  array([7.32462599, 2.44376297, 4.767

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

In [690]:
def extract_centered_subpart(arr, center, shape, fill_value=0):
    half_height = shape[0]
    half_width = shape[1]
    
    start_row = center[0] - half_height
    end_row = center[0] + half_height + 1
    start_col = center[1] - half_width
    end_col = center[1] + half_width + 1
    
    pad_top = max(0 - start_row, 0)
    pad_bottom = max(end_row - arr.shape[0], 0)
    pad_left = max(0 - start_col, 0)
    pad_right = max(end_col - arr.shape[1], 0)
    
    padded_arr = np.pad(arr, ((pad_top, pad_bottom), (pad_left, pad_right)), mode='constant', constant_values=fill_value)
    
    start_row += pad_top
    end_row += pad_top
    start_col += pad_left
    end_col += pad_left

    subpart = padded_arr[start_row:end_row, start_col:end_col]
    
    return subpart

arr = np.random.uniform(0,10,(5,5))

center = (1, 1)
shape = (3, 3)

subpart = extract_centered_subpart(arr, center, shape)
print("Extracted Subpart:")
print(subpart)
arr

Extracted Subpart:
[[0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         6.88220552 9.77261083 7.78238723 2.81389768
  3.17711617]
 [0.         0.         9.06885815 6.51705899 4.73349656 3.3925957
  4.94854901]
 [0.         0.         4.79909894 1.06949073 4.0376836  8.37095982
  6.61420402]
 [0.         0.         3.9596053  9.53330933 7.34078395 1.48454854
  4.05598222]
 [0.         0.         0.65861299 2.41031466 3.41146271 4.10991246
  4.11126532]]


array([[6.88220552, 9.77261083, 7.78238723, 2.81389768, 3.17711617],
       [9.06885815, 6.51705899, 4.73349656, 3.3925957 , 4.94854901],
       [4.79909894, 1.06949073, 4.0376836 , 8.37095982, 6.61420402],
       [3.9596053 , 9.53330933, 7.34078395, 1.48454854, 4.05598222],
       [0.65861299, 2.41031466, 3.41146271, 4.10991246, 4.11126532]])

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [714]:
# using func from problem-76
Z = np.arange(0,15)
sliding_window(Z, 4)

array([[ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [722]:
Z = np.random.uniform(0,10,(10,10))
rank = np.linalg.matrix_rank(Z)
print(rank), Z

10


(None,
 array([[0.45731996, 5.82009587, 4.85695027, 5.61813032, 7.31591074,
         5.20044075, 0.89194647, 2.49441672, 3.78177006, 5.4697502 ],
        [9.74598213, 4.20643532, 5.8773694 , 1.37652694, 2.62425169,
         6.49477992, 8.47627316, 2.02627433, 1.3109765 , 9.96792456],
        [9.13937776, 9.29757973, 1.28839885, 9.44974477, 2.57644456,
         2.58903288, 8.33645457, 9.54781812, 9.70062453, 5.92750168],
        [9.8294258 , 1.6430613 , 5.06657796, 4.89161941, 5.92324573,
         8.71953029, 7.68289587, 3.78796678, 5.67234737, 7.33595285],
        [2.43203256, 6.64416688, 5.95904232, 4.80752806, 2.08473108,
         8.26674198, 1.46022329, 4.91267819, 5.30065066, 2.41058064],
        [1.49614393, 1.60699968, 6.03248031, 6.2399667 , 4.63186752,
         2.01059954, 1.6037463 , 2.5364029 , 3.13691624, 8.23189731],
        [8.15157331, 9.33785935, 6.3133757 , 6.46254985, 4.00905134,
         8.63288145, 3.98627653, 3.08015287, 3.34103828, 9.96039772],
        [2.55458378,

#### 83. How to find the most frequent value in an array?

In [726]:
arr = np.array([1, 2, 3, 2, 2, 3, 1, 3, 3, 3])
most_frequent_value = np.bincount(arr).argmax()
print(most_frequent_value)

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [730]:
from numpy.lib.stride_tricks import sliding_window_view
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[0 2 1]
   [2 0 0]
   [2 1 1]]

  [[2 1 2]
   [0 0 3]
   [1 1 4]]

  [[1 2 2]
   [0 3 3]
   [1 4 1]]

  [[2 2 0]
   [3 3 0]
   [4 1 3]]

  [[2 0 2]
   [3 0 4]
   [1 3 4]]

  [[0 2 3]
   [0 4 3]
   [3 4 3]]

  [[2 3 2]
   [4 3 1]
   [4 3 2]]

  [[3 2 3]
   [3 1 0]
   [3 2 3]]]


 [[[2 0 0]
   [2 1 1]
   [0 4 0]]

  [[0 0 3]
   [1 1 4]
   [4 0 3]]

  [[0 3 3]
   [1 4 1]
   [0 3 3]]

  [[3 3 0]
   [4 1 3]
   [3 3 1]]

  [[3 0 4]
   [1 3 4]
   [3 1 4]]

  [[0 4 3]
   [3 4 3]
   [1 4 0]]

  [[4 3 1]
   [4 3 2]
   [4 0 2]]

  [[3 1 0]
   [3 2 3]
   [0 2 4]]]


 [[[2 1 1]
   [0 4 0]
   [4 2 1]]

  [[1 1 4]
   [4 0 3]
   [2 1 3]]

  [[1 4 1]
   [0 3 3]
   [1 3 4]]

  [[4 1 3]
   [3 3 1]
   [3 4 0]]

  [[1 3 4]
   [3 1 4]
   [4 0 2]]

  [[3 4 3]
   [1 4 0]
   [0 2 0]]

  [[4 3 2]
   [4 0 2]
   [2 0 2]]

  [[3 2 3]
   [0 2 4]
   [0 2 3]]]


 [[[0 4 0]
   [4 2 1]
   [3 1 0]]

  [[4 0 3]
   [2 1 3]
   [1 0 4]]

  [[0 3 3]
   [1 3 4]
   [0 4 2]]

  [[3 3 1]
   [3 4 0]
   [4 2 4]]

  [[3 1 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [738]:
class SymmetricArray:
    def __init__(self, size):
        self.size = size
        self.data = [[0] * size for _ in range(size)]

    def __getitem__(self, indices):
        i, j = indices
        return self.data[i][j]

    def __setitem__(self, indices, value):
        i, j = indices
        self.data[i][j] = value
        self.data[j][i] = value

size = 3
Z = SymmetricArray(size)

Z[0, 1] = 10
print(Z[0, 1])

10


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [753]:
p = 5
n = 3

matrices = [np.random.rand(n, n) for _ in range(p)]
vectors = [np.random.rand(n, 1) for _ in range(p)]

result = np.sum(np.matmul(matrices[i], vectors[i]) for i in range(p))

print(result)

[[3.57132693]
 [4.39698534]
 [3.29443636]]


C:\Users\mughe\AppData\Local\Temp\ipykernel_13820\3810731232.py:7: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  result = np.sum(np.matmul(matrices[i], vectors[i]) for i in range(p))


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

In [800]:
import numpy as np

# Example 16x16 array
arr = np.random.randint(1, 10, size=(16, 16))
block_size = 4
block_sums = np.zeros((4, 4), dtype=int)

for i in range(4):
    for j in range(4):
        block = arr[i*block_size:(i+1)*block_size, j*block_size:(j+1)*block_size]
        block_sum = np.sum(block)
        block_sums[i, j] = block_sum
        
print("Block-sums (4x4 blocks):")
arr, print(block_sums)


Block-sums (4x4 blocks):
[[85 80 81 92]
 [77 83 83 66]
 [86 73 73 74]
 [91 72 53 82]]


(array([[5, 3, 3, 1, 9, 1, 6, 9, 4, 9, 4, 2, 7, 1, 7, 2],
        [9, 8, 4, 1, 9, 1, 1, 2, 1, 4, 2, 6, 3, 7, 7, 8],
        [9, 7, 7, 4, 6, 5, 5, 2, 9, 6, 4, 6, 5, 7, 8, 7],
        [9, 2, 4, 9, 3, 9, 9, 3, 9, 3, 7, 5, 5, 7, 2, 9],
        [2, 7, 2, 8, 1, 6, 9, 6, 7, 5, 8, 6, 1, 5, 4, 2],
        [4, 2, 3, 5, 9, 7, 4, 4, 2, 8, 5, 3, 3, 6, 8, 5],
        [9, 4, 9, 1, 1, 4, 9, 8, 9, 2, 7, 5, 1, 1, 5, 9],
        [6, 9, 4, 2, 5, 2, 4, 4, 3, 9, 2, 2, 3, 1, 7, 5],
        [5, 4, 7, 9, 5, 3, 5, 2, 2, 7, 2, 8, 3, 7, 7, 3],
        [8, 7, 7, 8, 1, 3, 6, 5, 1, 9, 8, 3, 6, 5, 5, 2],
        [1, 3, 5, 3, 3, 7, 5, 6, 1, 3, 1, 6, 9, 5, 1, 4],
        [4, 6, 7, 2, 8, 1, 7, 6, 8, 4, 5, 5, 8, 1, 5, 3],
        [6, 3, 7, 8, 7, 7, 3, 8, 4, 1, 3, 6, 2, 6, 6, 2],
        [7, 7, 2, 9, 1, 4, 4, 8, 4, 5, 4, 8, 8, 3, 5, 7],
        [4, 4, 1, 6, 1, 4, 6, 2, 3, 5, 3, 2, 5, 5, 5, 2],
        [3, 7, 8, 9, 3, 5, 3, 6, 2, 1, 1, 1, 5, 8, 4, 9]]),
 None)

#### 88. How to implement the Game of Life using numpy arrays?

In [832]:
import numpy as np

def initialize_grid(size, prob_alive=0.2):
    return np.random.choice([0, 1], size=(size, size), p=[1-prob_alive, prob_alive])

def update(grid):
    size = grid.shape[0]
    new_grid = np.zeros_like(grid)
    
    for i in range(size):
        for j in range(size):
            neighbors_sum = (
                grid[(i-1) % size, (j-1) % size] + grid[(i-1) % size, j] + grid[(i-1) % size, (j+1) % size] +
                grid[i, (j-1) % size] + grid[i, (j+1) % size] +
                grid[(i+1) % size, (j-1) % size] + grid[(i+1) % size, j] + grid[(i+1) % size, (j+1) % size]
            )
            
            if grid[i, j] == 1 and (neighbors_sum < 2 or neighbors_sum > 3):
                new_grid[i, j] = 0
            elif grid[i, j] == 0 and neighbors_sum == 3:
                new_grid[i, j] = 1
            else:
                new_grid[i, j] = grid[i, j]
    
    return new_grid

def simulate_game_of_life(size, generations, prob_alive=0.2):
    grid = initialize_grid(size, prob_alive)
    
    for _ in range(generations):
        grid = update(grid)
    
    return grid

size = 20
generations = 50
prob_alive = 0.2

final_grid = simulate_game_of_life(size, generations, prob_alive)
print(final_grid)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 1 1 1 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0]
 [1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]]


In [838]:
np.set_printoptions(threshold=6)

#### 89. How to get the n largest values of an array

In [844]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5

indices = np.argpartition(arr, -n)[-n:]

largest_values = arr[indices]
largest_values

array([9995, 9996, 9997, 9998, 9999])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

In [848]:
np.set_printoptions(threshold=np.inf)

In [850]:
import numpy as np

def cartesian_product(*arrays):
    arrays = [np.asarray(arr) for arr in arrays]
    grids = np.meshgrid(*arrays, indexing='ij')
    stacked = np.stack(grids, axis=-1)
    product = stacked.reshape(-1, len(arrays))
    return product

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5])
arr3 = np.array([6, 7, 8])

result = cartesian_product(arr1, arr2, arr3)
print(result)


[[1 4 6]
 [1 4 7]
 [1 4 8]
 [1 5 6]
 [1 5 7]
 [1 5 8]
 [2 4 6]
 [2 4 7]
 [2 4 8]
 [2 5 6]
 [2 5 7]
 [2 5 8]
 [3 4 6]
 [3 4 7]
 [3 4 8]
 [3 5 6]
 [3 5 7]
 [3 5 8]]


In [852]:
np.set_printoptions(threshold=6)

#### 91. How to create a record array from a regular array?

In [854]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [866]:
regular_array = np.array([
    (1, 'Alice', 25),
    (2, 'Bob', 30),
    (3, 'Charlie', 35)
])

dtype = [('id', int), ('name', 'U10'), ('age', int)]
record_array = np.rec.fromrecords(regular_array, dtype=dtype)

print("Regular array:")
print(regular_array)

print("\nRecord array:")
print(record_array)

Regular array:
[['1' 'Alice' '25']
 ['2' 'Bob' '30']
 ['3' 'Charlie' '35']]

Record array:
[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 35)]


C:\Users\mughe\AppData\Local\Temp\ipykernel_13820\393765614.py:8: FutureWarning: fromrecords expected a list of tuples, may have received a list of lists instead. In the future that will raise an error
  record_array = np.rec.fromrecords(regular_array, dtype=dtype)


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [879]:
import numpy as np

Z = np.random.rand(1000000)  

%timeit Z_cubed_np = np.power(Z, 3)
%timeit Z_cubed_broadcast = Z * Z * Z
%timeit Z_cubed_python = np.einsum('i,i,i->i',Z,Z,Z)

print("NumPy (np.power) result:")
print(Z_cubed_np[:10])
print("\nNumPy (broadcasting) result:")
print(Z_cubed_broadcast[:10])
print("\nPure Python (list comprehension) result:")
print(Z_cubed_python[:10])

68.4 ms ± 7.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
13 ms ± 798 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
7.99 ms ± 735 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
NumPy (np.power) result:
[0.00289774 0.0051428  0.00571561 ... 0.64218858 0.1717853  0.01640023]

NumPy (broadcasting) result:
[0.01031198 0.414427   0.15376338 ... 0.28951232 0.00086205 0.05623271]

Pure Python (list comprehension) result:
[0.01031198 0.414427   0.15376338 ... 0.28951232 0.00086205 0.05623271]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [883]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [3, 1, 2],
              [6, 4, 5],
              [9, 7, 8],
              [2, 3, 1],
              [5, 6, 4]])

B = np.array([[1, 2],
              [4, 5]])

result_rows = []
for row in A:
    for b_row in B:
        if all(element in row for element in b_row):
            result_rows.append(row)
            break

result_rows_of_A = np.array(result_rows)

print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nRows of A containing elements of each row of B (regardless of order):")
print(result_rows_of_A)


Array A:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 ...
 [9 7 8]
 [2 3 1]
 [5 6 4]]

Array B:
[[1 2]
 [4 5]]

Rows of A containing elements of each row of B (regardless of order):
[[1 2 3]
 [4 5 6]
 [7 8 9]
 ...
 [9 7 8]
 [2 3 1]
 [5 6 4]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [893]:
arr = np.random.randint(0,5,(10,3))
output = arr[np.apply_along_axis(lambda row: len(set(row)) == len(row), 1, arr)]
arr, output

(array([[2, 0, 2],
        [1, 1, 4],
        [4, 2, 0],
        ...,
        [2, 2, 4],
        [2, 1, 2],
        [1, 0, 0]]),
 array([[4, 2, 0],
        [2, 3, 0],
        [2, 4, 3],
        [1, 2, 0]]))

#### 95. Convert a vector of ints into a matrix binary representation

In [905]:
np.set_printoptions(threshold=128)
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
binary_matrix = np.unpackbits(I[:, np.newaxis], axis=1)
I, binary_matrix

(array([  0,   1,   2,   3,  15,  16,  32,  64, 128], dtype=uint8),
 array([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 1, 1, 1, 1],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8))

#### 96. Given a two dimensional array, how to extract unique rows?

In [909]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])
unique_rows = np.unique(array, axis=0)
unique_rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [916]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

sum_A = np.einsum('i->', A)
print("Sum of elements of A:", sum_A)

elementwise_multiplication = np.einsum('i,i->i', A, B)
print("Element-wise multiplication:", elementwise_multiplication)

inner_product = np.einsum('i,i', A, B)
print("Inner product:", inner_product)

outer_product = np.einsum('i,j->ij', A, B)
print("Outer product:\n", outer_product)

Sum of elements of A: 5.328126045125186
Element-wise multiplication: [0.34184546 0.43676482 0.00959253 0.23061364 0.10210718 0.05979218
 0.74273915 0.87784066 0.13200539 0.15915248]
Inner product: 3.0924534863864683
Outer product:
 [[3.41845463e-01 4.83016747e-01 6.80721643e-03 2.83354187e-01
  2.31921228e-01 4.54713958e-01 4.45245684e-01 5.71561041e-01
  1.54268409e-01 5.04951380e-01]
 [3.09111587e-01 4.36764823e-01 6.15538218e-03 2.56221222e-01
  2.09713296e-01 4.11172205e-01 4.02610579e-01 5.16830438e-01
  1.39496228e-01 4.56599076e-01]
 [4.81718404e-01 6.80652756e-01 9.59252583e-03 3.99294247e-01
  3.26816459e-01 6.40769311e-01 6.27426903e-01 8.05426727e-01
  2.17390428e-01 7.11562385e-01]
 [2.78217972e-01 3.93113131e-01 5.54019333e-03 2.30613642e-01
  1.88753869e-01 3.70078322e-01 3.62372372e-01 4.65176728e-01
  1.25554523e-01 4.10965083e-01]
 [1.50503150e-01 2.12656155e-01 2.99699023e-03 1.24751393e-01
  1.02107177e-01 2.00195381e-01 1.96026816e-01 2.51639253e-01
  6.79192323e-02

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

In [920]:
import numpy as np

phi = np.arange(0, 10*np.pi, 0.1)
radius = 1
x_original = radius * phi * np.cos(phi)
y_original = radius * phi * np.sin(phi)

segment_lengths = (np.diff(x_original)**2 + np.diff(y_original)**2)**0.5
cumulative_distance = np.zeros_like(x_original)
cumulative_distance[1:] = np.cumsum(segment_lengths)

equidistant_distance = np.linspace(0, cumulative_distance.max(), 200)
x_interpolated = np.interp(equidistant_distance, cumulative_distance, x_original)
y_interpolated = np.interp(equidistant_distance, cumulative_distance, y_original)

print("Equidistant sampled points:")
for x, y in zip(x_interpolated, y_interpolated):
    print(f"({x:.2f}, {y:.2f})")


Equidistant sampled points:
(0.00, 0.00)
(-0.37, 1.74)
(-2.60, 0.98)
(-3.26, -1.34)
(-2.18, -3.53)
(-0.03, -4.70)
(2.43, -4.60)
(4.55, -3.34)
(5.92, -1.29)
(6.35, 1.14)
(5.82, 3.56)
(4.46, 5.62)
(2.47, 7.09)
(0.11, 7.83)
(-2.37, 7.79)
(-4.71, 7.00)
(-6.73, 5.56)
(-8.26, 3.60)
(-9.18, 1.31)
(-9.46, -1.16)
(-9.11, -3.61)
(-8.13, -5.89)
(-6.63, -7.87)
(-4.69, -9.42)
(-2.45, -10.47)
(-0.02, -10.99)
(2.46, -10.94)
(4.87, -10.33)
(7.09, -9.23)
(9.03, -7.67)
(10.59, -5.75)
(11.74, -3.55)
(12.41, -1.16)
(12.59, 1.32)
(12.28, 3.78)
(11.51, 6.14)
(10.30, 8.31)
(8.70, 10.21)
(6.79, 11.79)
(4.62, 13.00)
(2.26, 13.78)
(-0.20, 14.13)
(-2.68, 14.06)
(-5.12, 13.56)
(-7.42, 12.63)
(-9.54, 11.34)
(-11.42, 9.72)
(-12.99, 7.79)
(-14.24, 5.65)
(-15.12, 3.33)
(-15.61, 0.89)
(-15.72, -1.59)
(-15.42, -4.06)
(-14.76, -6.45)
(-13.73, -8.71)
(-12.36, -10.79)
(-10.70, -12.64)
(-8.78, -14.21)
(-6.65, -15.49)
(-4.36, -16.44)
(-1.94, -17.04)
(0.53, -17.29)
(3.01, -17.17)
(5.45, -16.72)
(7.80, -15.90)
(10.02, -14.78)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [938]:
n = 12

X = np.array([[1, 2, 7], [3, 4, 3], [0, 6, 0], [10, 1, 1], [2, 3, 5]])

is_multinomial = np.logical_and(np.all(X == X.astype(int), axis=1), np.sum(X, axis=1) == n)
selected_rows = X[is_multinomial]
selected_rows

array([[10,  1,  1]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [952]:
import numpy as np

X = np.random.randn(100) # random 1D array
N = 1000
bootstrap_means = np.zeros(N)

for i in range(N):
    bootstrap_sample = np.random.choice(X, size=len(X), replace=True)
    bootstrap_means[i] = np.mean(bootstrap_sample)

confidence_interval = np.percentile(bootstrap_means, [2.5, 97.5])

print("Bootstrapped 95% confidence interval for the mean:")
print(f"Lower bound: {confidence_interval[0]:.2f}")
print(f"Upper bound: {confidence_interval[1]:.2f}")

Bootstrapped 95% confidence interval for the mean:
Lower bound: -0.11
Upper bound: 0.25
